# Site settings
title: Development Setup Guide
description: Step-by-step guide to setting up a development environment for new developers
url: "https://josvoogtio.github.io/Project-ARiO/" # Replace with your GitHub username

# Theme settings
remote_theme: just-the-docs/just-the-docs
