# Site settings
title: Development Guide Project ARiO
description: Step-by-step guide to setting up a development environment for new developers
url: "https://josvoogtio.github.io/Project-ARiO/"

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Navigation structure
nav_order: 1
has_children: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/JosVoogtiO/Project-ARiO"

# Define navigation order for all pages
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"
  -
    scope:
      path: "index.md"
    values:
      nav_order: 1
  -
    scope:
      path: "new-project.md"
    values:
      nav_order: 2
  -
    scope:
      path: "exist-project.md"
    values:
      nav_order: 3